### ISSUE TITLE
Error: Invalid Json

### ISSUE THREAD

**Issue by andela-potemuyiwa** [tomas/needle#130]
You get an error of Invalid Json  when you set your Content-Type to be application/json when doing needle.post.

If you don't set Content-Type at all, the post operation works.

Moving forward, needle shouldn't force Content-Type on an options object when it has been explicitly set by the User.

**Comment by tomas** [comment]
Hi, 

Can you share a snippet of code? Sorry for the long delay, but I was quite swamped these past months. :)

**Comment by tomas** [comment]
Ping?

**Comment by mrft** [comment]
I think my issue is reletaed to this one: 

I had some code that used to work and stopped working recently.

I was trying to save a list of documents in bulk to couchdb. You do this by POSTing a document to <yourdburl>/_bulk_docs?include_docs=true

So I used to do something like this:
<code>
bulk = { "all-or-nothing": true, "docs": myArrayOfDocuments }
bulkString = JSON.stringify( bulk )
needle.post( fullUrl, bulkString, bulkRequestOptions, cb )
</code>

And just today it seems I suddenly needed to do the following to make it work:
<code>
bulk = { "all-or-nothing": true, "docs": myArrayOfDocuments }
needle.post( fullUrl, bulk, bulkRequestOptions, cb )
</code>

In this case, I did have the header set to "Content-Type': "application/json"
but I don't know if that actually makes a difference.

What surprises me is that it stopped working with a string (this code has worked for more than a year), because I should be able to do my own stringifying and be sure that that is what will be sent. Now it feels as if my string is being tampered with afterwards.

**Comment by tomas** [comment]
Needle did have some changes in the way data is fed to the request, but nothing major that should break anything. If you want to send an object as a JSON object, just pass the original object and set `json: true` in the options.

**Comment by tomas** [comment]
I'm not sure what the problem is, by the way.

**Comment by tomas** [comment]
If you take a look at the tests in `post_data_spec.js`, you'll see that post requests with a raw string doesn't tamper with your string. It only sets the content-type header to "application/x-www-form-urlencoded", which might be the problem.

In your example above, what does bulkRequestOptions look like? That way I can try to replicate both cases and see what's different.
