### ISSUE TITLE
Promise support? 

### ISSUE THREAD

**Issue by chrisjhoughton** [tomas/needle#147]
I've recently written up [a module](https://github.com/chrisjhoughton/archer) to wrap Needle in a JavaScript promise API, using [When.js](https://github.com/cujojs/when/) powered promises. 

Would be great to get promise support in the API as well - in conjunction with the existing callback based API.

If I did a PR for this would you accept?

**Comment by tomas** [comment]
I'd love to, as long as we keep things lean and mean. The problem is that When.js by itself seems bigger than Needle itself. Do you think you'd be able to do crack it with a lighter (or no) dependency? :)

**Comment by chrisjhoughton** [comment]
Hmmm, I see your point. Is your main concern _size_ or _efficiency_? For example:

* [D.js](https://github.com/malko/D.js) is one of the smallest out there - with 14KB core library, unminified
* [Bluebird](https://github.com/petkaantonov/bluebird) claims it offers "unmatched performance"

Neither of the above have any dependencies.

When.js also has very solid performance, but offers a bit more in the way of power & flexibility which might not be needed here.

Getting this done with _no_ dependency probably isn't an option - meeting the Promises/A+ specification in an efficient way is no mean feat. 

What are your thoughts? Any of the above libraries could work well but Bluebird might be the most appropriate.

**Comment by meehow** [comment]
Using not-native promise implementation should be optional. In many projects they use something like [native-or-bluebird](https://github.com/normalize/native-or-bluebird).

**Comment by tomas** [comment]
From those two options, D.js looks like a much better candidate because it aims at being minimal just as needle does (the [minified script](https://github.com/malko/D.js/blob/master/lib/D.min.js) is 3.77KB by the way). There's also [Q](https://github.com/kriskowal/q) which in fact is currently used in some of needle's tests.

To be honest I'm not really sure where to go with this. The callback based approach works for a lot of people and I don't want to force them into using promises if they don't want to -- it needs to be optional. Do you think it's possible to support promises without breaking the stream (no callback) mode?

Maybe the way to go is skip using a  library altogether and rewrite the codebase entirely using ES6 features and publish it as a separate package.

**Comment by clayzermk1** [comment]
Why do you need to include a promise library as a dependency? Libraries like Bluebird turn regular node-style callbacks into promises with ease. I have no issue using needle with Bluebird 2.x at the moment.

Alternatively, you could do something like the the [node-mongodb driver](https://github.com/mongodb/node-mongodb-native/blob/c06f14931e3e90806f81355ea7148648136c50c2/lib/aggregation_cursor.js#L75) does throughout their code. Pass in an optional promise library to use, otherwise uses a fallback. No bloat, compatible with various external libraries.

**Comment by chrisjhoughton** [comment]
@tomas why does it matter what size the minified script is? It's running on the server side - minifying has nothing to do with it? (Also FYI - When.js minified is ~5KB)

@meehow that solution looks promising.

@clayzermk1 - because less code to write :)

**Comment by bisubus** [comment]
I would highly recommend tiny `pify`, I believe it is the most popular promisifier (apart from Bluebird), it is also implementation-agnostic.

Promisification introduces breaking changes and disables streaming. I guess this should be a wrapper package. It is normal to have `*-as-promised` counterparts for popular callback-driven packages.

**Comment by tomas** [comment]
@bisubus yeah, I think that's the way to go. I don't have much time now but I'll take a look when I have a minute. if you want to give it a shot too, you're more than welcome. :)

**Comment by bisubus** [comment]
@tomas The thing that could be done on library level is exposing `setPromise` method (quite conventional for providing custom promise inplementation) on `needle` and `toPromise` method (quite conventional too) on stream object.

Here's a wrapper I'm using locally.

```
'use strict';

var needle = require('needle');
var pify = require('pify');

needle.promisify = function promisify(_Promise) {
	if (!_Promise) {
		if (typeof Promise !== 'undefined') {
			_Promise = Promise;
		} else {
			return needle;
		}
	}

	return pify(needle, _Promise, {
		multiArgs: true,
		include: ['head', 'get', 'post', 'put', 'patch', 'delete', 'request']
	});
};

module.exports = needle.promisify();
```

 Feel free to post this as a repo, it is maintenance-free solution but it requires some love from package owner on major version releases and API changes (wrapper package from @chrisjhoughton in the OP misses `patch` method that was added later).

**Comment by MarkHerhold** [comment]
@bisubus @tomas 
Could we just put the above script in an examples folder in this repository? That seems like the simplest and easiest solution for everyone. Anyone who wants to use it can just copy it to their own repo and it can be maintained along with the main needle repo.

**Comment by dandv** [comment]
Maybe now that Node 8 includes even async/await without a flag, the choice of which Promises library to use is moot?

**Comment by bisubus** [comment]
@dandv This may be future proof habit to stick to global `Promise` if it's there, but not everyone is going to use Node 8 any time soon. And this mostly depends on what Node versions are supported by the library, I guess it supports 0.x and higher for now.

**Comment by kristianmandrup** [comment]
Why is Promise support not included as an option somehow?! This is 2017, it's the current year :P

**Comment by tomas** [comment]
@kristianmandrup If you read the project's readme you'll see that the goal of Needle is to avoid bloat wherever possible. Unfortunately, a big chunk of developers are [still running](https://semaphoreci.com/blog/2016/10/12/nodejs-versions-used-in-commercial-projects-2016-edition.html) Node 0.x, which means the only way they can use Promises is by including a library that just by ifself it bigger that Needle. And that kind of defeats the whole point.

Now, I *do* want to support Promises if they're available natively, in contrast to a polyfill-based approach that was the only option when this issue was originally opened. Nowadays, though. it certainly is, so it's just the lack of time what's holding me from implementing it. 

So if you want to give it a shot, you're most welcome!

**Comment by tomas** [comment]
Ok, I'll take a short dive into the code now and see if I can pull it off in a simple and clean way. :)

**Comment by kristianmandrup** [comment]
Thanks :) You can check for native promise support, ie. if `Promise` is defined.

**Comment by tomas** [comment]
Ok I think I have something. Doesn't break any tests and allows for full backwards compatibility. My strategy was to assign the Promise version directly to the main exports object. This way, the existing methods keep working as usual (`needle.get`, `needle.post`, etc), but if you want to use the promisified version, you just call `needle()` directly:

```
const needle = require('needle')
needle(method, uri, data, options).then(...).catch(...);
```

Where the data and options arguments are optional. For example:

```
needle('get', 'server.com', { username: 'someone' }).then(function(resp) {
  console.log(resp.statusCode, resp.headers, resp.body);
}).catch(function(err) {
  console.error(err.message);
})
```

Or:

```
var opts = { follow_max: 1, ... };
needle('post', 'server.com/endpoint', { foo: 'bar' }, opts).then(function(resp) {
  ...
}).catch(function(err) {
  ...
})
```

The method argument can also be omitted, in which case it defaults to `get`, unless `data` is present. In this case a `post` request is assumed.

**Comment by dandv** [comment]
@bisubus: Node added native Promise support in v4. No need to target Node 8. v0.x are deprecated.

**Comment by bisubus** [comment]
@dandv There's still a lot of applications for Node 0.x and a lot of support for it from NPM packages. A dev is free to use any Node version he/she wishes in private projects, but breaking reverse compatibility for no obvious reason is bad manners for sure. Any way, this is a concern for repo owner.

**Comment by tomas** [comment]
Ok guys it's in the master branch if you want to try it out. I need to get back to work now but once I write a few tests and update the docs I'll be pushing it to npm.

**Needle**ss to say, thanks everyone for your input!

**Comment by kristianmandrup** [comment]
Please add docs/demo on `Promise` usage on `Readme` page. Thanks!

**Comment by AlexeyTerentievGit** [comment]
How is it going?

**Comment by tomas** [comment]
![image](https://user-images.githubusercontent.com/10574/29134404-7dffacca-7d04-11e7-991c-5dd58cf944cc.png)

It *is*. :)

**Comment by AlexeyTerentievGit** [comment]
Yeeah! Thanks!

**Comment by kasper3** [comment]
I am struggling with mapping Promise to await/async pattern.
Could we please have an example of await/async in the README?

**Comment by ash0080** [comment]
try..catch with await/async can't catch error
