### ISSUE TITLE
Custom xml2js options

### ISSUE THREAD

**Issue by alexwhitman** [tomas/needle#153]
It would be useful to be able to pass custom options to the xml2js parser.  The current options are
```js
{
    explicitRoot : true,
    explicitArray: false
}
```
but the parser supports [many more](https://www.npmjs.com/package/xml2js#options).

**Comment by tomas** [comment]
Good point. Something like `xml_parser_options: { foo: 'bar' }` could do.

Is there a specific one you think we should add to the defaults?

**Comment by alexwhitman** [comment]
The defaults work well but for this particular project I'm also using `emptyTag: null` and `mergeAttrs: true`.

**Comment by tomas** [comment]
Gotcha. Care to submit a PR? :)

**Comment by alexwhitman** [comment]
I can do.  How would you like the options passed from `needle.js` through to `parsers.js`?

**Comment by tomas** [comment]
Hmm. It actually requires some intervention. Let me give a try and I'll get back to you.

**Comment by tomas** [comment]
Ok, after some tinkering I think the cleanest approach is to simply load a new xml2js.Parser using the defaults, which thankfully are exposed by the module so you can change any option as long as you do it before loading needle:

```js
require('xml2js').defaults['0.2'].mergeAttrs = true;

var needle = require('needle');
needle.get(...)
```

Defaulting to xml2js's defaults also makes more sense because that's what most people would probably use or expect.

What do you think?

**Comment by tomas** [comment]
@alexwhitman Did the above solution work for you? I'm closing this issue for the time being, but feel free to reopen it if you feel there's a better approach for this.
