### ISSUE TITLE
Needle parses in streams mode

### ISSUE THREAD

**Issue by terinjokes** [tomas/needle#68]
Needle still parses JSON and XML data, even when no callback is provided. This causes the stream to be in object mode.

Is this expected behavior? In my mind, parsing should happen in streams mode. (But obviously this can trivially be disabled by passing in `parsed: false`)

**Comment by monolithed** [comment]
```
var stream = needle.request('post', url, {}, {
	decode: false,
	parse: false
});

stream.pipe(response);

stream.on('end', function () {
      // Never be fired without `parse: false`
});
```

Please pay attention to this point in the documentation!

**Comment by tomas** [comment]
@monolithed Is that so? What URL are you testing with?

**Comment by monolithed** [comment]
@tomas, public url like https://e.mail.ru

**Comment by tomas** [comment]
@monolithed Can you share a full code example? I don't know where the `response` object you show comes from.

**Comment by monolithed** [comment]
@tomas, 

``` 
app.use(express.cookieParser());

app.use(function (request, response, next) {
    get_cookies(function () {
          request.cookies = result.cookies;
          next();
   });
});

app.use('/api', function (request, response, next) {
	var url = 'https://e.mail.ru/api' + request.url;

	var stream = needle.request(request.method, url, request.body, {
		cookies: request.cookies,
		parse  : false
	});

	stream.pipe(response);
});
```

Could not close connection without `parse: false`. It seems very strange...

**Comment by tomas** [comment]
Ok, gonna test it now. Which needle version are you running?

**Comment by tomas** [comment]
I just tested and running the latest Needle (from git, not npm) I do get the 'end' event emitted. This might have to do with a few [recent changes](https://github.com/tomas/needle/commit/06d8c71de16f85ac210c5a001f85b21d598ab2ca) related to the Connection header.

I haven't pushed a new version to NPM because I need to update the documentation first. However you can safely run the latest version of git since all new major changes have been thoroughly covered with tests.

**Comment by monolithed** [comment]
0.11.0, thanks
